version: '3.9'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000


  # I use this to view the DynamoDB tables in the browser
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"  # Link to the `dynamodb` service
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
    depends_on:
      - dynamodb

  pnpm:
    image: node:20
    container_name: pnpm
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "apt update && apt install -y curl git zsh && curl -fsSL https://get.pnpm.io/install.sh | sh && (curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh || echo 'skipp installing zsh already installed') && tail -f /dev/null"]
    depends_on:
      - dynamodb
    env_file:
      - ./apps/api/.env
    environment:
      - SHELL=zsh
    ports:
      - "1338:1337"

volumes:
  dynamo_data:
    driver: local