export type AbilitiesEnum = ClientsAbilitiesEnum | OwnersAbilitiesEnum;

export enum ClientsAbilitiesEnum {

  CLIENT_MANAGE_ORGANIZATIONS = 'CLIENT_MANAGE_ORGANIZATION',
  CLIENT_UPDATE_ORGANIZATIONS = 'CLIENT_UPDATE_ORGANIZATION',
  CLIENT_DELETE_ORGANIZATIONS = 'CLIENT_DELETE_ORGANIZATION',

  CLIENT_MANAGE_THEME = 'CLIENT_MANAGE_THEME',
  CLIENT_READ_THEME = 'CLIENT_READ_THEME',
  CLIENT_CREATE_THEME = 'CLIENT_CREATE_THEME',
  CLIENT_UPDATE_THEME = 'CLIENT_UPDATE_THEME',
  CLIENT_DELETE_THEME = 'CLIENT_DELETE_THEME',

  CLIENT_MANAGE_GROUP = 'CLIENT_MANAGE_GROUP',
  CLIENT_READ_GROUP = 'CLIENT_READ_GROUP',
  CLIENT_CREATE_GROUP = 'CLIENT_CREATE_GROUP',
  CLIENT_UPDATE_GROUP = 'CLIENT_UPDATE_GROUP',
  CLIENT_DELETE_GROUP = 'CLIENT_DELETE_GROUP',

  CLIENT_MANAGE_GROUP_PARTICIPANT = 'CLIENT_MANAGE_GROUP_PARTICIPANT',
  CLIENT_READ_GROUP_PARTICIPANT = 'CLIENT_READ_GROUP_PARTICIPANT',
  CLIENT_CREATE_GROUP_PARTICIPANT = 'CLIENT_CREATE_GROUP_PARTICIPANT',
  CLIENT_UPDATE_GROUP_PARTICIPANT = 'CLIENT_UPDATE_GROUP_PARTICIPANT',
  CLIENT_DELETE_GROUP_PARTICIPANT = 'CLIENT_DELETE_GROUP_PARTICIPANT',

  CLIENT_MANAGE_PRESENCE = 'CLIENT_MANAGE_PRESENCE',
  CLIENT_READ_PRESENCE = 'CLIENT_READ_PRESENCE',
  CLIENT_CREATE_PRESENCE = 'CLIENT_CREATE_PRESENCE',
  CLIENT_UPDATE_PRESENCE = 'CLIENT_UPDATE_PRESENCE',
  CLIENT_DELETE_PRESENCE = 'CLIENT_DELETE_PRESENCE',

  CLIENT_MANAGE_FEEDBACKS = 'CLIENT_MANAGE_FEEDBACKS',
  CLIENT_READ_FEEDBACKS = 'CLIENT_READ_FEEDBACKS',
  CLIENT_CREATE_FEEDBACKS = 'CLIENT_CREATE_FEEDBACKS',
  CLIENT_UPDATE_FEEDBACKS = 'CLIENT_UPDATE_FEEDBACKS',
  CLIENT_DELETE_FEEDBACKS = 'CLIENT_DELETE_FEEDBACKS',

  CLIENT_VIEW_DASHBOARD = 'CLIENT_VIEW_DASHBOARD',

  CLIENT_VIEW_PAPERS = 'CLIENT_VIEW_PAPERS',
  CLIENT_GENERATE_PAPERS = 'CLIENT_GENERATE_PAPERS',
  CLIENT_VALIDATE_PAPERS = 'CLIENT_VALIDATE_PAPERS',
}

export enum OwnersAbilitiesEnum {
  // organizations
  OWNER_MANAGE_ORGANIZATIONS = 'OWNER_MANAGE_ORGANIZATIONS',
  OWNER_DELETE_ORGANIZATION = 'OWNER_DELETE_ORGANIZATION',

  // organizations participnats
  OWNER_MANAGE_ORGANIZATION_PARTICIPANT = 'OWNER_MANAGE_ORGANIZATION_PARTICIPANT',
  OWNER_CREATE_ORGANIZATION_PARTICIPANT = 'OWNER_CREATE_ORGANIZATION_PARTICIPANT',
  OWNER_DELETE_ORGANIZATION_PARTICIPANT = 'OWNER_DELETE_ORGANIZATION_PARTICIPANT',
  OWNER_UPDATE_ORGANIZATION_PARTICIPANT = 'OWNER_UPDATE_ORGANIZATION_PARTICIPANT',
  OWNER_READ_ORGANIZATION_PARTICIPANT = 'OWNER_READ_ORGANIZATION_PARTICIPANT',

  // organizations participnats
  // OWNER_MANAGE_ORGANIZATION_PARTICIPANT = 'OWNER_MANAGE_ORGANIZATION_PARTICIPANT',
  // OWNER_CREATE_ORGANIZATION_PARTICIPANT = 'OWNER_CREATE_ORGANIZATION_PARTICIPANT',
  // OWNER_DELETE_ORGANIZATION_PARTICIPANT = 'OWNER_DELETE_ORGANIZATION_PARTICIPANT',
  // OWNER_UPDATE_ORGANIZATION_PARTICIPANT = 'OWNER_UPDATE_ORGANIZATION_PARTICIPANT',
  // OWNER_READ_ORGANIZATION_PARTICIPANT = 'OWNER_READ_ORGANIZATION_PARTICIPANT',



  // organizations
  OWNER_UPDATE_ORGANIZATION = 'OWNER_UPDATE_ORGANIZATION',
  OWNER_READ_ORGANIZATION = 'OWNER_READ_ORGANIZATION',
  OWNER_ACTIVATE_ORGANIZATION = 'OWNER_ACTIVATE_ORGANIZATION',
  OWNER_DEACTIVATE_ORGANIZATION = 'OWNER_DEACTIVATE_ORGANIZATION',

  // themes
  OWNER_READ_THEMES = 'OWNER_READ_THEMES',

  // gotups
  OWNER_READ_GROUPS = 'OWNER_READ_GROUPS',

  // group parit
  OWNER_READ_GROUP_PARTICIPANTS = 'OWNER_READ_GROUP_PARTICIPANTS',
}

